CREATE TABLE tb_customers (
                              customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              full_name VARCHAR(255) NOT NULL,
                              id_number VARCHAR(50),
                              email VARCHAR(255),
                              phone_number VARCHAR(50),
                              address VARCHAR(255),
                              city VARCHAR(100),
                              state VARCHAR(100),
                              zip_code VARCHAR(20),
                              country VARCHAR(100),
                              total_spent DECIMAL(12,2),
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);