CREATE TABLE tb_orders (
                           order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           customer_id BIGINT NOT NULL,
                           status VARCHAR(50) NOT NULL,
                           total_amount DECIMAL(10,2) NOT NULL,
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT fk_orders_customer
                               FOREIGN KEY (customer_id)
                                   REFERENCES tb_customers(customer_id)
);