CREATE TABLE tb_restaurants (
                                restaurant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                status VARCHAR(20) NOT NULL,
                                full_name VARCHAR(255) NOT NULL,
                                fiscal_code VARCHAR(50),
                                phone_number VARCHAR(50),
                                email VARCHAR(255),
                                address VARCHAR(255),
                                city VARCHAR(100),
                                state VARCHAR(100),
                                zip_code VARCHAR(20),
                                country VARCHAR(100),
                                description TEXT,
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);