CREATE TABLE tb_product_categories (
                                       category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       category_name VARCHAR(100) NOT NULL
);