CREATE TABLE tb_products (
                             product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(255) NOT NULL,
                             description TEXT,
                             price DECIMAL(10,2) NOT NULL,
                             status VARCHAR(20) NOT NULL,
                             category_id BIGINT NOT NULL,
                             restaurant_id BIGINT NOT NULL,
                             CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES tb_product_categories(category_id),
                             CONSTRAINT fk_product_restaurant FOREIGN KEY (restaurant_id) REFERENCES tb_restaurants(restaurant_id)
);