CREATE TABLE tb_order_items (
                                order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                order_id BIGINT NOT NULL,
                                product_id BIGINT NOT NULL,
                                quantity INT NOT NULL,
                                unit_price DECIMAL(10,2) NOT NULL,
                                CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES tb_orders(order_id),
                                CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES tb_products(product_id)
);